#!/usr/bin/env python3
"""Generate fulltext CSV + COPY statements from text sources in repo and external tree."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXTERNAL_ROOT = Path(r"D:\开源项目源码")

OUT_DIR = ROOT / "sample-data"
OUT_CSV = OUT_DIR / "fulltext_source.csv"
OUT_COPY = OUT_DIR / "fulltext_source_copy.sql"

SKIP_DIRS = {
    ".git",
    ".cursor",
    "node_modules",
    "build",
    "bin",
    "bin-test",
    "target",
    "dist",
    ".gradle",
    "__pycache__",
}

TEXT_EXTENSIONS = {
    ".java",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".css",
    ".scss",
    ".less",
    ".html",
    ".htm",
    ".md",
    ".txt",
    ".json",
    ".xml",
    ".vue",
    ".py",
    ".sql",
    ".yml",
    ".yaml",
    ".properties",
    ".sh",
    ".bat",
    ".ps1",
    ".gradle",
    ".kt",
    ".cpp",
    ".c",
    ".h",
    ".hpp",
    ".go",
    ".rs",
    ".rb",
    ".php",
    ".csv",
    ".svg",
    ".ini",
    ".conf",
    ".cfg",
    ".toml",
}


def java_string_hashcode(text: str) -> int:
    h = 0
    for ch in text:
        h = (31 * h + ord(ch)) & 0xFFFFFFFF
    if h >= 0x80000000:
        h -= 0x100000000
    return h


def should_skip(path: Path) -> bool:
    return any(part in SKIP_DIRS for part in path.parts)


def iter_source_files() -> list[Path]:
    files: list[Path] = []

    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or should_skip(path):
            continue
        rel = path.relative_to(ROOT)
        suffix = path.suffix.lower()
        if suffix == ".java":
            files.append(path)
        elif rel.parts and rel.parts[0] == "docs" and suffix in {".html", ".md"}:
            files.append(path)

    if EXTERNAL_ROOT.exists():
        for path in sorted(EXTERNAL_ROOT.rglob("*")):
            if not path.is_file() or should_skip(path):
                continue
            if path.suffix.lower() in TEXT_EXTENSIONS:
                files.append(path)

    return files


def write_copy_sql(csv_path: Path, row_count: int, file_count: int, line_count: int, skipped: int) -> None:
    csv_posix = csv_path.as_posix()
    with OUT_COPY.open("w", encoding="utf-8", newline="\n") as out:
        out.write(
            "-- Auto-generated by scripts/generate-fulltext-java-inserts.py\n"
            f"-- CSV rows: {row_count} (files: {file_count}, source lines: {line_count}, skipped blank: {skipped})\n"
            "-- Columns: hashstr, txt1, txt2, txt3, txt4\n"
            "-- txt1/txt2/txt3 = file name only; txt4 = original line (punctuation kept)\n\n"
            "-- Recommended: psql client-side \\copy\n"
            "\\copy fulltext(hashstr, txt1, txt2, txt3, txt4) FROM "
            f"'{csv_posix}' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');\n\n"
            "-- Server-side COPY (path must exist on PostgreSQL server)\n"
            "COPY fulltext(hashstr, txt1, txt2, txt3, txt4)\n"
            f"FROM '{csv_posix}'\n"
            "WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');\n"
        )


def main() -> int:
    file_count = 0
    line_count = 0
    skipped_blank = 0
    row_count = 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8", newline="") as csv_out:
        writer = csv.writer(csv_out, lineterminator="\n")
        writer.writerow(["hashstr", "txt1", "txt2", "txt3", "txt4"])

        for source_path in iter_source_files():
            file_count += 1
            file_name = source_path.name
            try:
                fh = source_path.open(encoding="utf-8", errors="replace")
            except OSError:
                continue
            with fh:
                for raw in fh:
                    line_count += 1
                    txt4 = raw.rstrip("\n\r")
                    if not txt4.strip():
                        skipped_blank += 1
                        continue
                    hashstr = str(java_string_hashcode(txt4))
                    row_count += 1
                    writer.writerow([hashstr, file_name, file_name, file_name, txt4])

    write_copy_sql(OUT_CSV, row_count, file_count, line_count, skipped_blank)

    print(f"Files: {file_count}, source lines: {line_count}, rows: {row_count}")
    print(f"Skipped blank lines: {skipped_blank}")
    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_COPY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
